import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'id' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string, fallback?: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  id: {
    // Nav Sections
    'nav.section.core': 'Utama',
    'nav.section.project': 'Ruang Kerja Proyek',
    'nav.section.general': 'Umum & Operasional',
    'nav.section.governance': 'Tata Kelola & Manajemen',
    'nav.section.system': 'Sistem',

    // Nav Items
    'nav.dashboard': 'Dashboard',
    'nav.projects': 'Daftar Proyek',
    'nav.kanban': 'Papan Orkestrasi',
    'nav.timeline': 'Jadwal Proyek',
    'nav.cockpit': 'Kokpit Klien',
    'nav.files': 'Berkas & Dokumen',
    'nav.globalTimeline': 'Jadwal Global',
    'nav.chat': 'Chat',
    'nav.projectChat': 'Chat Proyek',
    'nav.resources': 'Sumber Daya & Tim',
    'nav.timeTracking': 'Presensi Jam Kerja',
    'nav.clients': 'Manajemen Klien',
    'nav.templates': 'Template Alur Kerja',
    'nav.activity': 'Log Audit Aktivitas',
    'nav.users': 'Manajemen Pengguna',
    'nav.reports': 'Laporan & Analitik',
    'nav.notifications': 'Notifikasi',
    'nav.settings': 'Pengaturan',

    // Common Actions & Labels
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.delete': 'Hapus',
    'common.edit': 'Ubah',
    'common.detail': 'Rincian',
    'common.create': 'Buat Baru',
    'common.search': 'Cari...',
    'common.filter': 'Saring',
    'common.refresh': 'Muat Ulang',
    'common.export': 'Ekspor',
    'common.close': 'Tutup',
    'common.loading': 'Memuat...',
    'common.all': 'Semua',
    'common.status': 'Status',
    'common.actions': 'Tindakan',
    'common.back': 'Kembali',
    'common.view': 'Lihat',
    'common.confirm': 'Konfirmasi',

    // Header & Profile Dropdown
    'header.selectProject': 'Pilih Proyek Aktif',
    'header.noProjects': 'Tidak ada proyek',
    'header.searchPlaceholder': 'Cari proyek, tugas... (⌘K)',
    'header.notifications': 'Notifikasi',
    'header.unread': 'belum dibaca',
    'header.markAllRead': 'Tandai semua dibaca',
    'header.noNotifications': 'Tidak ada notifikasi baru',
    'header.closeNotifications': 'Tutup notifikasi',
    'header.toggleTheme': 'Ganti Tema',
    'header.toggleLanguage': 'Ganti Bahasa',
    'header.quickRoleSwitcher': 'Ganti Peran Pengguna',
    'header.switchPersona': 'Ganti Peran Pengguna',
    'header.accountSettings': 'Akun & Pengaturan',
    'header.logout': 'Keluar',
    'header.newTask': 'Tugas Baru',
    'header.viewAllNotifications': 'Lihat Semua Notifikasi →',

    // Notifications Page
    'notifications.title': 'Notifikasi',
    'notifications.subtitle': 'Pantau aktivitas proyek, penugasan tugas baru, dan pengumuman sistem secara langsung.',
    'notifications.markAllRead': 'Tandai Semua Dibaca',
    'notifications.tabAll': 'Semua',
    'notifications.tabUnread': 'Belum Dibaca',
    'notifications.tabMentions': 'Sebutan & Permintaan',
    'notifications.syncInfo': 'Sinkronisasi otomatis dengan basis data • Klik untuk membaca',
    'notifications.empty': 'Tidak ada notifikasi',
    'notifications.emptyDesc': 'Semua notifikasi sudah dibaca atau belum ada aktivitas baru.',
    'notifications.entityInfo': 'Informasi Entitas',
    'notifications.categoryType': 'Kategori Tipe',
    'notifications.receivedTime': 'Waktu Diterima',
    'notifications.openRelated': 'Buka Halaman Terkait',

    // Orchestration Board Page
    'board.title': 'Papan Orkestrasi',
    'board.badge': '12 Tahap Operasional',
    'board.subtitle': 'Alur pengiriman 12 tahap terintegrasi. Geser kartu antar tahap atau klik Tahap Berikutnya.',
    'board.createTask': 'Tugas Baru',
    'board.currentProject': 'Proyek Aktif',
    'board.allProjects': 'Semua Proyek',
    'board.searchPlaceholder': 'Cari tugas, kode, penanggung jawab...',
    'board.allPriorities': 'Semua Prioritas',
    'board.nextStage': 'Tahap Berikutnya',
    'board.noTasks': 'Belum ada tugas di tahap ini',

    // Workflow Templates Page
    'templates.title': 'Manajemen Template Alur Kerja',
    'templates.subtitle': 'Gunakan template alur kerja teruji untuk mempercepat inisiasi proyek, memastikan standar arsitektur terpenuhi sejak awal.',
    'templates.createWithTemplate': 'Buat Proyek dengan Template',
    'templates.useTemplate': 'Gunakan Template Ini',
    'templates.viewTasks': 'Lihat Tugas Awal',
    'templates.starterTasksCount': 'tugas otomatis',
    'templates.duplicate': 'Duplikasi Template',
    'templates.emptyTasks': 'Template ini adalah alur kerja kosong. Tugas dapat ditambahkan secara manual di Papan Orkestrasi.',

    // Time Tracking & Reports Page
    'timetracking.title': 'Presensi Jam Kerja, Audit Aktivitas & Laporan SLA',
    'timetracking.subtitle': 'Catatan presensi terverifikasi dan telemetri siklus hidup proyek.',
    'timetracking.timesheet': 'Lembar Waktu',
    'timetracking.activityAudit': 'Audit Aktivitas',
    'timetracking.executiveAnalytics': 'Analitik Eksekutif',
    'timetracking.liveStopwatch': 'Stopwatch Jam Kerja Aktif',
    'timetracking.notClockedIn': 'Belum Masuk Kerja — Pilih Tugas & Mulai Jam Kerja',
    'timetracking.activeShiftSince': 'Jam Kerja Aktif sejak',
    'timetracking.clockIn': 'Masuk Kerja',
    'timetracking.clockOut': 'Keluar Kerja & Simpan Durasi',
    'timetracking.linkTask': 'Hubungkan ke Tugas (Opsional)',
    'timetracking.notesPlaceholder': 'Catatan aktivitas jam kerja...',
    'timetracking.recordedTimesheets': 'Riwayat Presensi Jam Kerja Tersimpan',
    'timetracking.engineer': 'Anggota Tim',
    'timetracking.projectTask': 'Proyek / Tugas',
    'timetracking.clockInTime': 'Jam Masuk',
    'timetracking.clockOutTime': 'Jam Keluar',
    'timetracking.duration': 'Durasi',
    'timetracking.notes': 'Catatan',
    'timetracking.noEntries': 'Belum ada catatan presensi tersimpan.',
    'timetracking.immutableAudit': 'Jejak Audit Proyek Terverifikasi',
    'timetracking.immutableSubtitle': 'Mutasi operasional sistem pada proyek dan tugas tanpa manipulasi.',
    'timetracking.sprintVelocity': 'Kecepatan Sprint',
    'timetracking.slaCompliance': 'Tingkat Kepatuhan SLA',
    'timetracking.clientResponseSla': 'SLA Respon Klien',

    // Settings Page
    'settings.title': 'Pengaturan Sistem',
    'settings.subtitle': 'Kelola profil akun, preferensi bahasa, zona waktu, dan keamanan aplikasi SDK.',
    'settings.profile': 'Profil Pengguna',
    'settings.profileDesc': 'Informasi akun dan kontak Anda.',
    'settings.preferences': 'Preferensi Bahasa & Regional',
    'settings.preferencesDesc': 'Pengaturan bahasa antarmuka, zona waktu, dan notifikasi email.',
    'settings.language': 'Bahasa Tampilan',
    'settings.languageDesc': 'Pilih bahasa untuk seluruh tampilan antarmuka aplikasi.',
    'settings.timezone': 'Zona Waktu',
    'settings.security': 'Keamanan & Akun',
    'settings.securityDesc': 'Pengaturan kata sandi dan autentikasi sesi.',
    'settings.saveChanges': 'Simpan Pengaturan',
    'settings.savedSuccess': 'Pengaturan bahasa dan profil berhasil diperbarui!',
    'settings.emailNotifs': 'Notifikasi Email',
    'settings.emailNotifsDesc': 'Kirim ringkasan harian saat ada pembaruan tugas.',

    // Dashboard - General & Workspaces
    'dashboard.welcome': 'Selamat Datang kembali',
    'dashboard.activeProjects': 'Proyek Aktif',
    'dashboard.healthScore': 'Skor Kesehatan',
    'dashboard.myTasks': 'Tugas Saya',
    'dashboard.todaySchedule': 'Jadwal Hari Ini',
    'dashboard.clockIn': 'Presensi Masuk',
    'dashboard.clockOut': 'Presensi Keluar',
    'dashboard.recentActivity': 'Aktivitas Terkini',
    'dashboard.allProjects': 'Daftar Seluruh Proyek',
    'dashboard.staffWorkspace': 'Ruang Kerja Staf',
    'dashboard.staffRole': 'Peran: STAF',
    'dashboard.staffSubtitle': 'Pencatatan jam kerja, daftar tugas aktif, dan pelacakan sprint Anda.',
    'dashboard.leadWorkspace': 'Pusat Project Lead',
    'dashboard.leadRole': 'Peran: PROJECT LEAD',
    'dashboard.leadSubtitle': 'Pemantauan proyek binaan, delegasi tugas sprint, dan respon persetujuan klien.',
    'dashboard.adminWorkspace': 'Dashboard Eksekutif',
    'dashboard.adminRole': 'Peran: ADMINISTRATOR',
    'dashboard.adminSubtitle': 'Ringkasan status proyek, alokasi beban kerja, dan kesehatan operasional SDK.',
    
    // Staff Presensi (Clock In/Out)
    'dashboard.workingActive': 'Sedang Bekerja',
    'dashboard.attendanceStandby': 'Presensi Kerja',
    'dashboard.statusActive': 'Aktif',
    'dashboard.statusStandby': 'Siaga',
    'dashboard.clockInPrompt': 'Mulai hari kerja Anda dengan menekan tombol Masuk Kerja di samping.',
    'dashboard.clockInAction': 'Masuk Kerja',
    'dashboard.clockOutAction': 'Keluar Kerja',
    'dashboard.selectProject': 'Pilih Proyek...',
    'dashboard.assignedTasks': 'Tugas Ditugaskan',
    'dashboard.activeTasksPending': 'tugas aktif belum selesai',
    'dashboard.completedTasksSprint': 'Tugas Selesai (Sprint Ini)',
    'dashboard.completionRate': 'tingkat penyelesaian',
    'dashboard.weeklyAllocation': 'Alokasi Mingguan',
    'dashboard.hoursUnit': 'Jam',
    'dashboard.myTasksTitle': 'Tugas Saya',
    'dashboard.myTasksSubtitle': 'Kelola progres tugas secara langsung tanpa berpindah tab.',
    'dashboard.filterAll': 'Semua',
    'dashboard.filterInProgress': 'Sedang Berjalan',
    'dashboard.filterDone': 'Selesai',
    'dashboard.noTasksFilter': 'Tidak ada tugas yang sesuai dengan filter saat ini.',
    'dashboard.startWork': 'Mulai Kerja',
    'dashboard.submitReview': 'Ajukan Review',
    'dashboard.completeTask': 'Selesai',

    // Project Lead Hub
    'dashboard.clientOverdueAlert': 'Tugas Sedang Menunggu Respon Klien',
    'dashboard.clientOverdueDesc': 'Klien belum merespon verifikasi. Segera tindak lanjuti via chat untuk mencegah potensi keterlambatan timeline proyek.',
    'dashboard.followUpChat': 'Tindak Lanjut via Chat',
    'dashboard.projectsLed': 'Proyek yang Dipimpin',
    'dashboard.activeOrchestration': 'Dalam orkestrasi aktif',
    'dashboard.tasksNeedAttention': 'Tugas Butuh Perhatian',
    'dashboard.blockedCritical': 'Terhambat / Prioritas Kritis',
    'dashboard.waitingClientResponse': 'Menunggu Respon Klien',
    'dashboard.pendingClientReview': 'Menunggu review klien',
    'dashboard.healthyProjects': 'Proyek Sehat',
    'dashboard.myGuidedProjects': 'Proyek Binaan Saya',
    'dashboard.myGuidedSubtitle': 'Akses cepat ke Kanban, Timeline Gantt, dan Cockpit Klien.',
    'dashboard.clientLabel': 'Klien:',
    'dashboard.progressLabel': 'Progres Implementasi',

    // Executive / Admin Dashboard
    'dashboard.operationalPipeline': 'Proyek dalam alur operasional',
    'dashboard.openSprintTasks': 'Tugas Sprint Terbuka',
    'dashboard.activeSprintBadge': 'Sprint Aktif',
    'dashboard.teamWorkingTasks': 'Tugas sedang dikerjakan tim',
    'dashboard.completedProjects': 'Proyek Selesai',
    'dashboard.deliveredBadge': 'Terserah Terima',
    'dashboard.handedOverVerified': 'Proyek serah terima & terverifikasi',
    'dashboard.projectHealth': 'Kesehatan Proyek',
    'dashboard.healthyBadge': 'Sehat',
    'dashboard.formulaVerified': 'Formula 30/30/20/20 terverifikasi',
    'dashboard.recentProjectsHealth': 'Proyek Terkini & Status Kesehatan',
    'dashboard.recentProjectsSubtitle': 'Status, progres, dan skor kesehatan proyek di database',
    'dashboard.viewAllProjects': 'Lihat semua proyek',
    'dashboard.colProject': 'Proyek',
    'dashboard.colClient': 'Klien',
    'dashboard.colHealth': 'Kesehatan',
    'dashboard.colProgress': 'Progres',
    'dashboard.colStage': 'Fase',
    'dashboard.loadingProjects': 'Memuat data proyek...',
    'dashboard.noProjectsRegistered': 'Belum ada proyek yang terdaftar',
    'dashboard.recentActivityLog': 'Log Aktivitas Terkini',
    'dashboard.loadingActivities': 'Memuat log aktivitas...',
    'dashboard.noRecentActivity': 'Belum ada aktivitas terbaru',
    'dashboard.newProjectBtn': 'Proyek Baru',

    // Project Details Modal
    'modal.clientOrg': 'Klien / Organisasi',
    'modal.deliveryModel': 'Model Pengiriman',
    'modal.workflowTemplate': 'Templat Alur Kerja',
    'modal.targetRelease': 'Target Rilis',
    'modal.projectProgress': 'Kemajuan Proyek',
    'modal.quickModuleActions': 'Aksi Cepat Modul Proyek',
    'modal.kanbanBoard': 'Papan Kanban',
    'modal.ganttTimeline': 'Timeline Gantt',
    'modal.clientCockpit': 'Client Cockpit',
    'modal.filesRepository': 'Berkas Dokumen',
    'modal.setActiveProject': 'Jadikan Proyek Aktif',
    'modal.close': 'Tutup',

    // Client Cockpit Page
    'cockpit.title': 'Client Cockpit',
    'cockpit.subtitle': 'Progres proyek, pencapaian milestone, deliverable terverifikasi, dan pelacakan revisi.',
    'cockpit.projectChat': 'Chat Proyek',
    'cockpit.actionRequired': 'Aksi Diperlukan:',
    'cockpit.actionRequiredSuffix': 'Deliverable Membutuhkan Review Anda',
    'cockpit.actionRequiredDesc': 'Silakan periksa berkas deliverable yang telah diselesaikan oleh tim SDK untuk melanjutkan ke milestone berikutnya.',
    'cockpit.approve': 'Setujui',
    'cockpit.requestRevision': 'Minta Revisi',
    'cockpit.executiveOverview': 'Ringkasan Eksekutif',
    'cockpit.welcome': 'Selamat datang,',
    'cockpit.welcomeDesc': 'Berikut adalah ringkasan progres verifikasi produk digital Anda secara transparan.',
    'cockpit.currentStage': 'Fase Saat Ini',
    'cockpit.targetCompletion': 'Target Penyelesaian',
    'cockpit.projectHealth': 'Kesehatan Proyek',
    'cockpit.overallProgress': 'Tingkat Penyelesaian Keseluruhan',
    'cockpit.tasksCompletedOf': 'tugas selesai',
    'cockpit.milestonesTitle': 'Milestone Proyek & Titik Serah Terima',
    'cockpit.milestonesSubtitle': 'Titik kontrol penyerahan fungsionalitas dan persetujuan bertahap.',
    'cockpit.deliverablesTitle': 'Dokumen & Deliverable Terverifikasi',
    'cockpit.deliverablesSubtitle': 'Setiap rilis deliverable membutuhkan persetujuan resmi dari Anda.',
    'cockpit.uploadFileBtn': 'Unggah Berkas',
    'cockpit.uploadModalTitle': 'Unggah Berkas & Dokumen Klien',
    'cockpit.uploadModalDesc': 'Unggah dokumen spesifikasi, umpan balik revisi, atau dokumen penandatanganan resmi.',
    'cockpit.uploadFileLabel': 'Pilih Berkas',
    'cockpit.uploadCategoryLabel': 'Kategori Berkas',
    'cockpit.uploadNotesLabel': 'Catatan / Deskripsi Singkat',
    'cockpit.uploadSubmit': 'Unggah Sekarang',
    'cockpit.uploadedFilesTitle': 'Berkas yang Diunggah Klien & Tim',
    'cockpit.revisionTrackerTitle': 'Pelacak Siklus Revisi',
    'cockpit.revisionTrackerSubtitle': 'Transparansi status dan dampak keterlambatan dari setiap permintaan perubahan.',
    'cockpit.potentialDelay': 'Potensi Delay',
    'cockpit.days': 'Hari',

    // Login Page
    'login.welcome': 'Selamat datang di SDK',
    'login.signin': 'Masuk',
    'login.noAccount': 'Belum punya akun?',
    'login.signup': 'Daftar',
    'login.usernameOrEmail': 'Masukkan username atau alamat email',
    'login.usernameOrEmailPlaceholder': 'Username atau alamat email',
    'login.password': 'Masukkan Kata Sandi',
    'login.passwordPlaceholder': 'Kata sandi',
    'login.forgotPassword': 'Lupa Kata Sandi',
    'login.submit': 'Masuk',
    'login.submitting': 'Memverifikasi...',
    'login.quickRoleTitle': 'Akses Cepat Pengujian Role (RBAC)',
    'login.themeTooltip': 'Ganti Tema (Terang / Gelap)',
    'login.langTooltip': 'Ganti Bahasa (ID / EN)',
    'login.brandTagline': 'Platform Manajemen & Orkestrasi Proyek Digital Terpusat',
    'login.invalidCredentials': 'Username atau email tidak ditemukan.',
    'login.passwordRequired': 'Kata sandi wajib diisi.',
    'login.successMessage': 'Berhasil masuk sebagai',
  },
  en: {
    // Nav Sections
    'nav.section.core': 'Core',
    'nav.section.project': 'Project Workspace',
    'nav.section.general': 'General & Operations',
    'nav.section.governance': 'Governance & Management',
    'nav.section.system': 'System',

    // Nav Items
    'nav.dashboard': 'Dashboard',
    'nav.projects': 'Projects Directory',
    'nav.kanban': 'Orchestration Board',
    'nav.timeline': 'Project Timeline',
    'nav.cockpit': 'Client Cockpit',
    'nav.files': 'Files & Documents',
    'nav.globalTimeline': 'Global Timeline',
    'nav.chat': 'Chat',
    'nav.projectChat': 'Project Chat',
    'nav.resources': 'Resources & Team',
    'nav.timeTracking': 'Time Tracking',
    'nav.clients': 'Client Management',
    'nav.templates': 'Workflow Templates',
    'nav.activity': 'Activity Audit Log',
    'nav.users': 'User Management',
    'nav.reports': 'Reports & Analytics',
    'nav.notifications': 'Notifications',
    'nav.settings': 'Settings',

    // Common Actions & Labels
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.detail': 'Details',
    'common.create': 'Create New',
    'common.search': 'Search...',
    'common.filter': 'Filter',
    'common.refresh': 'Refresh',
    'common.export': 'Export',
    'common.close': 'Close',
    'common.loading': 'Loading...',
    'common.all': 'All',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.back': 'Back',
    'common.view': 'View',
    'common.confirm': 'Confirm',

    // Header & Profile Dropdown
    'header.selectProject': 'Select Active Project',
    'header.noProjects': 'No projects available',
    'header.searchPlaceholder': 'Search projects, tasks... (⌘K)',
    'header.notifications': 'Notifications',
    'header.unread': 'unread',
    'header.markAllRead': 'Mark all as read',
    'header.noNotifications': 'No new notifications',
    'header.closeNotifications': 'Close notifications',
    'header.toggleTheme': 'Toggle Theme',
    'header.toggleLanguage': 'Switch Language',
    'header.quickRoleSwitcher': 'Switch User Role',
    'header.switchPersona': 'Switch User Role',
    'header.accountSettings': 'Account & Settings',
    'header.logout': 'Sign Out',
    'header.newTask': 'New Task',
    'header.viewAllNotifications': 'View All Notifications →',

    // Notifications Page
    'notifications.title': 'Notifications',
    'notifications.subtitle': 'Monitor project activity, new task assignments, and system announcements in real-time.',
    'notifications.markAllRead': 'Mark All as Read',
    'notifications.tabAll': 'All',
    'notifications.tabUnread': 'Unread',
    'notifications.tabMentions': 'Mentions & Requests',
    'notifications.syncInfo': 'Real-time database sync • Click to read',
    'notifications.empty': 'No notifications',
    'notifications.emptyDesc': 'All notifications have been read or there is no new activity.',
    'notifications.entityInfo': 'Entity Information',
    'notifications.categoryType': 'Category Type',
    'notifications.receivedTime': 'Received Time',
    'notifications.openRelated': 'Open Related Page',

    // Orchestration Board Page
    'board.title': 'Orchestration Board',
    'board.badge': '12 Stages • Live Database',
    'board.subtitle': 'End-to-end 12-stage delivery pipeline. Drag and drop cards across any stage or advance via Next Stage.',
    'board.createTask': 'New Task',
    'board.currentProject': 'Current Project',
    'board.allProjects': 'All Projects',
    'board.searchPlaceholder': 'Search tasks, code, assignee...',
    'board.allPriorities': 'All Priorities',
    'board.nextStage': 'Next Stage',
    'board.noTasks': 'No tasks in this stage',

    // Workflow Templates Page
    'templates.title': 'Workflow Templates Management',
    'templates.subtitle': 'Use battle-tested workflow templates to accelerate project initiation, ensuring architectural standards are met from day one.',
    'templates.createWithTemplate': 'Create Project with Template',
    'templates.useTemplate': 'Use This Template',
    'templates.viewTasks': 'View Starter Tasks',
    'templates.starterTasksCount': 'starter tasks',
    'templates.duplicate': 'Duplicate Template',
    'templates.emptyTasks': 'This template is a blank workflow. Tasks can be created manually in the Kanban board.',

    // Time Tracking & Reports Page
    'timetracking.title': 'Time Tracking, Activity Audit & SLA Reports',
    'timetracking.subtitle': 'Auditable timesheets and lifecycle telemetrics.',
    'timetracking.timesheet': 'Timesheet',
    'timetracking.activityAudit': 'Activity Audit',
    'timetracking.executiveAnalytics': 'Executive Analytics',
    'timetracking.liveStopwatch': 'Live Shift Stopwatch',
    'timetracking.notClockedIn': 'Not Clocked In — Select Task & Start Shift',
    'timetracking.activeShiftSince': 'Active Shift since',
    'timetracking.clockIn': 'Clock In',
    'timetracking.clockOut': 'Clock Out & Log Duration',
    'timetracking.linkTask': 'Link to Task (Optional)',
    'timetracking.notesPlaceholder': 'Shift activity notes...',
    'timetracking.recordedTimesheets': 'Recorded Shift Timesheets',
    'timetracking.engineer': 'Team Member',
    'timetracking.projectTask': 'Project / Task',
    'timetracking.clockInTime': 'Clock In',
    'timetracking.clockOutTime': 'Clock Out',
    'timetracking.duration': 'Duration',
    'timetracking.notes': 'Notes',
    'timetracking.noEntries': 'No timesheet entries recorded yet.',
    'timetracking.immutableAudit': 'Immutable Project Audit Trail',
    'timetracking.immutableSubtitle': 'Immutable operational mutations across projects and tasks.',
    'timetracking.sprintVelocity': 'Sprint Velocity',
    'timetracking.slaCompliance': 'SLA Compliance Rate',
    'timetracking.clientResponseSla': 'Client Response SLA',

    // Settings Page
    'settings.title': 'System Settings',
    'settings.subtitle': 'Manage account profile, language preferences, timezone, and SDK security.',
    'settings.profile': 'User Profile',
    'settings.profileDesc': 'Your account credentials and contact details.',
    'settings.preferences': 'Language & Regional Preferences',
    'settings.preferencesDesc': 'Configure interface language, timezone, and email alerts.',
    'settings.language': 'Display Language',
    'settings.languageDesc': 'Choose interface language across the application.',
    'settings.timezone': 'Timezone',
    'settings.security': 'Security & Account',
    'settings.securityDesc': 'Manage password and session authentication.',
    'settings.saveChanges': 'Save Settings',
    'settings.savedSuccess': 'Language and profile preferences saved successfully!',
    'settings.emailNotifs': 'Email Notifications',
    'settings.emailNotifsDesc': 'Send daily summaries when tasks are updated.',

    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.activeProjects': 'Active Projects',
    'dashboard.healthScore': 'Health Score',
    'dashboard.myTasks': 'My Tasks',
    'dashboard.todaySchedule': 'Today Schedule',
    'dashboard.clockIn': 'Clock In Now',
    'dashboard.clockOut': 'Clock Out',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.allProjects': 'All Projects List',
    'dashboard.staffWorkspace': 'Staff Workspace',
    'dashboard.staffRole': 'Role: STAFF',
    'dashboard.staffSubtitle': 'Work hour logging, active task list, and your sprint tracking.',
    'dashboard.leadWorkspace': 'Project Lead Hub',
    'dashboard.leadRole': 'Role: PROJECT LEAD',
    'dashboard.leadSubtitle': 'Guided projects monitoring, sprint task delegation, and client approval responses.',
    'dashboard.adminWorkspace': 'Executive Dashboard',
    'dashboard.adminRole': 'Role: ADMINISTRATOR',
    'dashboard.adminSubtitle': 'Project status summary, team workload allocation, and SDK operational health.',

    // Staff Presensi (Clock In/Out)
    'dashboard.workingActive': 'Currently Working',
    'dashboard.attendanceStandby': 'Work Attendance',
    'dashboard.statusActive': 'Active',
    'dashboard.statusStandby': 'Standby',
    'dashboard.clockInPrompt': 'Start your workday by clicking the Clock In button beside.',
    'dashboard.clockInAction': 'Clock In',
    'dashboard.clockOutAction': 'Clock Out',
    'dashboard.selectProject': 'Select Project...',
    'dashboard.assignedTasks': 'Assigned Tasks',
    'dashboard.activeTasksPending': 'active tasks pending',
    'dashboard.completedTasksSprint': 'Completed Tasks (This Sprint)',
    'dashboard.completionRate': 'completion rate',
    'dashboard.weeklyAllocation': 'Weekly Allocation',
    'dashboard.hoursUnit': 'Hours',
    'dashboard.myTasksTitle': 'My Tasks',
    'dashboard.myTasksSubtitle': 'Manage task progress directly without switching tabs.',
    'dashboard.filterAll': 'All',
    'dashboard.filterInProgress': 'In Progress',
    'dashboard.filterDone': 'Completed',
    'dashboard.noTasksFilter': 'No tasks match the current filter.',
    'dashboard.startWork': 'Start Work',
    'dashboard.submitReview': 'Submit Review',
    'dashboard.completeTask': 'Complete',

    // Project Lead Hub
    'dashboard.clientOverdueAlert': 'Tasks Waiting for Client Response',
    'dashboard.clientOverdueDesc': 'Client has not responded to verification. Follow up via chat to prevent potential project timeline delays.',
    'dashboard.followUpChat': 'Follow-up via Chat',
    'dashboard.projectsLed': 'Projects Led',
    'dashboard.activeOrchestration': 'In active orchestration',
    'dashboard.tasksNeedAttention': 'Tasks Needing Attention',
    'dashboard.blockedCritical': 'Blocked / Critical priority',
    'dashboard.waitingClientResponse': 'Awaiting Client Response',
    'dashboard.pendingClientReview': 'Pending client review',
    'dashboard.healthyProjects': 'Healthy Projects',
    'dashboard.myGuidedProjects': 'My Guided Projects',
    'dashboard.myGuidedSubtitle': 'Quick access to Kanban, Gantt Timeline, and Client Cockpit.',
    'dashboard.clientLabel': 'Client:',
    'dashboard.progressLabel': 'Implementation Progress',

    // Executive / Admin Dashboard
    'dashboard.operationalPipeline': 'Projects in operational pipeline',
    'dashboard.openSprintTasks': 'Open Sprint Tasks',
    'dashboard.activeSprintBadge': 'Active Sprint',
    'dashboard.teamWorkingTasks': 'Tasks in progress by team',
    'dashboard.completedProjects': 'Completed Projects',
    'dashboard.deliveredBadge': 'Delivered',
    'dashboard.handedOverVerified': 'Handed over & verified projects',
    'dashboard.projectHealth': 'Project Health',
    'dashboard.healthyBadge': 'Healthy',
    'dashboard.formulaVerified': '30/30/20/20 formula verified',
    'dashboard.recentProjectsHealth': 'Recent Projects & Health Status',
    'dashboard.recentProjectsSubtitle': 'Status, progress, and project health scores in database',
    'dashboard.viewAllProjects': 'View all projects',
    'dashboard.colProject': 'Project',
    'dashboard.colClient': 'Client',
    'dashboard.colHealth': 'Health',
    'dashboard.colProgress': 'Progress',
    'dashboard.colStage': 'Stage',
    'dashboard.loadingProjects': 'Loading project data...',
    'dashboard.noProjectsRegistered': 'No projects registered yet',
    'dashboard.recentActivityLog': 'Recent Activity Log',
    'dashboard.loadingActivities': 'Loading activity log...',
    'dashboard.noRecentActivity': 'No recent activity yet',
    'dashboard.newProjectBtn': 'New Project',

    // Project Details Modal
    'modal.clientOrg': 'Client / Organization',
    'modal.deliveryModel': 'Delivery Model',
    'modal.workflowTemplate': 'Workflow Template',
    'modal.targetRelease': 'Target Release',
    'modal.projectProgress': 'Project Progress',
    'modal.quickModuleActions': 'Quick Module Actions',
    'modal.kanbanBoard': 'Kanban Board',
    'modal.ganttTimeline': 'Gantt Timeline',
    'modal.clientCockpit': 'Client Cockpit',
    'modal.filesRepository': 'Files Repository',
    'modal.setActiveProject': 'Set as Active Project',
    'modal.close': 'Close',

    // Client Cockpit Page
    'cockpit.title': 'Client Cockpit',
    'cockpit.subtitle': 'Project progress, milestones, verified deliverables, and revision tracking.',
    'cockpit.projectChat': 'Project Chat',
    'cockpit.actionRequired': 'Action Required:',
    'cockpit.actionRequiredSuffix': 'Deliverables Require Your Review',
    'cockpit.actionRequiredDesc': 'Please review deliverable files completed by the SDK team to proceed to the next milestone.',
    'cockpit.approve': 'Approve',
    'cockpit.requestRevision': 'Request Revision',
    'cockpit.executiveOverview': 'Executive Overview',
    'cockpit.welcome': 'Welcome,',
    'cockpit.welcomeDesc': 'Here is the transparent progress summary of your digital product.',
    'cockpit.currentStage': 'Current Stage',
    'cockpit.targetCompletion': 'Target Completion',
    'cockpit.projectHealth': 'Project Health',
    'cockpit.overallProgress': 'Overall Completion Rate',
    'cockpit.tasksCompletedOf': 'tasks completed',
    'cockpit.milestonesTitle': 'Project Milestones & Delivery Checkpoints',
    'cockpit.milestonesSubtitle': 'Control checkpoints for incremental delivery and phased sign-offs.',
    'cockpit.deliverablesTitle': 'Verified Documents & Deliverables',
    'cockpit.deliverablesSubtitle': 'Each deliverable release requires formal sign-off from you.',
    'cockpit.uploadFileBtn': 'Upload File',
    'cockpit.uploadModalTitle': 'Upload Client File & Document',
    'cockpit.uploadModalDesc': 'Upload specifications, revision feedback, or formal sign-off documents.',
    'cockpit.uploadFileLabel': 'Select File',
    'cockpit.uploadCategoryLabel': 'File Category',
    'cockpit.uploadNotesLabel': 'Notes / Brief Description',
    'cockpit.uploadSubmit': 'Upload Now',
    'cockpit.uploadedFilesTitle': 'Files Uploaded by Client & Team',
    'cockpit.revisionTrackerTitle': 'Revision Lifecycle Tracker',
    'cockpit.revisionTrackerSubtitle': 'Transparent status and timeline delay impacts of each change request.',
    'cockpit.potentialDelay': 'Potential Delay',
    'cockpit.days': 'Days',

    // Login Page
    'login.welcome': 'Welcome to SDK',
    'login.signin': 'Sign in',
    'login.noAccount': 'No Account ?',
    'login.signup': 'Sign up',
    'login.usernameOrEmail': 'Enter your username or email address',
    'login.usernameOrEmailPlaceholder': 'Username or email address',
    'login.password': 'Enter your Password',
    'login.passwordPlaceholder': 'Password',
    'login.forgotPassword': 'Forgot Password',
    'login.submit': 'Sign in',
    'login.submitting': 'Verifying...',
    'login.quickRoleTitle': 'Quick Persona Role Access (RBAC)',
    'login.themeTooltip': 'Toggle Theme (Light / Dark)',
    'login.langTooltip': 'Switch Language (ID / EN)',
    'login.brandTagline': 'Centralized Project Orchestration & Management Platform',
    'login.invalidCredentials': 'Username or email not found.',
    'login.passwordRequired': 'Password is required.',
    'login.successMessage': 'Successfully logged in as',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('sdk_language');
    if (saved === 'id' || saved === 'en') {
      return saved;
    }
    return 'id'; // Default Indonesian as requested
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('sdk_language', lang);
    document.documentElement.lang = lang;
  };

  const toggleLanguage = () => {
    setLanguage(language === 'id' ? 'en' : 'id');
  };

  useEffect(() => {
    document.documentElement.lang = language;
    localStorage.setItem('sdk_language', language);
  }, [language]);

  const t = (key: string, fallback?: string): string => {
    const langDict = translations[language] || translations.id;
    if (langDict[key]) {
      return langDict[key];
    }
    // Fallback to ID if key is not found in EN
    if (translations.id[key]) {
      return translations.id[key];
    }
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
