const fs = require('fs');
const path = require('path');

const pdfPath = path.join(__dirname, 'test-out.pdf');
const data = fs.readFileSync(pdfPath);

// Find all page objects
// In PDF generated by Chrome / Skia:
// Pages have /Type /Page and reference /Contents
// A simpler way: split by /Type /Page
const str = data.toString('latin1');
const pageChunks = str.split(/\/Type\s*\/Page\b/);
console.log('Total page chunks found:', pageChunks.length - 1);

// We want to find which page each chapter heading appears on:
const headingsToFind = [
  { id: 'pendahuluan', title: '1. Pendahuluan' },
  { id: 'roles', title: '2. Daftar Role' },
  { id: 'getting-started', title: '3. Panduan Memulai' },
  { id: 'admin', title: '4. Panduan Lengkap Administrator' },
  { id: 'project-lead', title: '5. Panduan Project Lead' },
  { id: 'staff', title: '6. Panduan Staff Engineer' },
  { id: 'client', title: '7. Panduan Pengguna Klien' },
  { id: 'flow', title: '8. Alur Kerja Terpadu' },
  { id: 'faq', title: '9. Pertanyaan yang Sering' },
  { id: 'troubleshooting', title: '10. Panduan Troubleshooting' },
  { id: 'contact', title: '11. Kontak & Dukungan' }
];

// Let's search in page objects or use pdf-lib / puppeteer
// Since Chrome includes text stream, let's inspect where titles appear
headingsToFind.forEach(h => {
  // Find index in str
  const escaped = h.title.replace(/[-/\\^$*+?.()|[\]{}]/g, '\\$&');
  // In PDF, text might be like (1. Pendahuluan) or split
  // Let's search simple substrings
  const words = h.title.split(' ');
  const firstWord = words[0]; // e.g. "1.", "2.", "3.", etc.
  const secondWord = words[1]; // e.g. "Pendahuluan"
  console.log(`Searching for ${h.title}...`);
});
